name: Linux

# Run on PR requests. And on master itself.
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  TestLinux:
    name: Linux, Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # 2018
          - python: 3.7
            pins: "sqlalchemy==1.3.* alembic==1.8.* geoalchemy2==0.9.*"
            extras: "test,simulation_templates"
          # 2019
          - python: 3.8
            pins: "sqlalchemy==1.3.* alembic==1.8.* geoalchemy2==0.9.*"
            extras: "test,simulation_templates"
          # 2021
          - python: 3.9
            pins: "sqlalchemy==1.4.30 alembic==1.8.* geoalchemy2==0.10.*"
            extras: "test,simulation_templates"
          # current
          - python: "3.10"
            pins: ""
            extras: "test,simulation_templates"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install psql, sqlite3 and spatialite
        run: |
          sudo apt-get install --yes --no-install-recommends sqlite3 libsqlite3-mod-spatialite
  
      - name: Install python dependencies
        shell: bash
        run: |
          pip install --disable-pip-version-check --upgrade pip setuptools wheel
          pip install ${{ matrix.pins }} .[${{ matrix.extras }}] pytest-cov
          pip list

      - name: Run tests
        shell: bash
        run: |
          pytest --cov threedi_modelchecker
