name: Linux

# Run on PR requests. And on master itself.
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  TestLinux:
    name: Linux, Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # 2017
          - python: 3.6
            pins: "sqlalchemy==1.2.* geoalchemy2==0.9.* alembic==0.9.*"
            extras: "test,simulation_templates,postgis"
          # 2018
          - python: 3.7
            pins: "sqlalchemy==1.2.* alembic==1.2.*"
            extras: "test,simulation_templates,postgis"
          # 2019
          - python: 3.8
            pins: "sqlalchemy==1.3.* alembic==1.4.*"
            extras: "test,simulation_templates,postgis"
          # current
          - python: 3.9
            pins: ""
            extras: "test,simulation_templates,postgis,migrations"

    services:
      postgis:
        image: mdillon/postgis
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgis
          POSTGRES_PASSWORD: mysecret

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install psql, sqlite3 and spatialite
        run: |
          sudo apt-get install --yes --no-install-recommends postgresql-client sqlite3 libsqlite3-mod-spatialite
  
      - name: Load test postgis database
        shell: bash
        run: | 
          psql -h localhost -d postgis -U postgis -w  < tests/data/postgres/emtpy_postgres.sql
        env:
          PGPASSWORD: mysecret

      - name: Install python dependencies
        shell: bash
        run: |
          pip install --disable-pip-version-check --upgrade pip setuptools wheel
          pip install ${{ matrix.pins }} .[${{ matrix.extras }}] pytest-cov
          pip list

      - name: Run tests
        shell: bash
        run: |
          pytest --cov threedi_modelchecker
